### ISSUE TITLE
CSV formátum

### ISSUE THREAD

**Issue by szaboadamtamas** [szaboadamtamas/nocbeo#1]
Hónap.csv

```
1. Év Hónap neve;Frissítette;Frissítés Ideje
2. Csoport neve;;;;
3. Kód;Név;Munkakódok
```

Index.csv
```
Szeptemberi beosztás;2016.09.01;2016.09.30;szeptember.csv
Októberi beosztás;2016.10.01;2016.10.30;oktober.csv
Novemberi beosztás;2016.11.01;2016.11.30;november.csv
```

**Comment by Szabot1210** [comment]
Kell a sor végére is pontosvessző?
Itt is tudok küldeni filet?

**Comment by Szabot1210** [comment]
2017-04-06 20:42 GMT+02:00 Ádám Szabó <notifications@github.com>:

**Comment by Szabot1210** [comment]
Index file-t megcsináltam

Színezés a CSS-ben leírjam, hogy melyik mit jelent?



2017-04-06 20:42 GMT+02:00 Ádám Szabó <notifications@github.com>:

**Comment by Szabot1210** [comment]
![image](https://cloud.githubusercontent.com/assets/22646863/24788000/86611cd2-1b6b-11e7-8201-9b98abc91e85.png)

Ez látszik?

**Comment by Szabot1210** [comment]
Ékezetek a file nevekben maradjanak?

**Comment by Szabot1210** [comment]
Elküldöm ékezettelenítve a file neveket, mert az ékezetes fileket a WEBDAV
nem engedi törölni. :) az Index.cs-ben is így szerepelnek
Megnéztem az EXCEL a sor végére nem tesz pontosvesszőt és CR és LF -et
tesz, erre cseréltem



2017. április 7. 8:02 Tamás Szabó írta, <szabot1210@gmail.com>:

**Comment by Szabot1210** [comment]
Nagyon jó ! :)
De azt vettem észre, hogy néhány sor végén nincs rács.
Valamint szerintem a hétvégi oszlop színezés lehetne egy kicsit erősebb Majd ezt mutasd meg.
Mit kell majd felmásolnom a WEBDAV-ra?
![image](https://cloud.githubusercontent.com/assets/22646863/24894323/db94bdc8-1e89-11e7-86e1-b06625d1e167.png)

**Comment by Szabot1210** [comment]
OK A "K"-at megcsináltam.
Felmásoltam a SNOC oldalra és működik csak az ékezetek nem jók a neveknél (UTF-8 :( )
https://nocbeo.t-online.hu/nocbeo/

Az UTF-8 al nem jutok dűlőre. Ezt te kézzel (pl notepad)  fordítottad át?
Elvileg a CSV fileben jól van és amikor felmásolom ott is megadom,. hogy UTF-8 legyen a character set. Még nézem...

**Comment by Szabot1210** [comment]
VBA BÓL NEM TUDOM az UTF8 at megcsinálni

**Comment by Szabot1210** [comment]
Megoldottam az UTF-8 problémáját
